form:
    class: Silex\Provider\FormServiceProvider
    parameters:
        form.secret: REPLACE_THIS_NOT_SO_SECRET_SECRET

monolog:
    class: Silex\Provider\MonologServiceProvider
    parameters:
        monolog.level: 300
        monolog.logfile: "%path.logs%/%mode%.log"

translation:
    class: Silex\Provider\TranslationServiceProvider
    parameters:
        locale: en
        locale_fallback: en

twig:
    class: Silex\Provider\TwigServiceProvider
    parameters:
        twig.path: "%path.views%"
        twig.options:
            auto_reload: %debug%
            cache: "%path.cache%/views"
            debug: %debug%

url_generator:
    class: Silex\Provider\UrlGeneratorServiceProvider

validator:
    class: Silex\Provider\ValidatorServiceProvider
