twig:
    class: Silex\Provider\TwigServiceProvider
    parameters:
        twig.path: "%path.views%"
        twig.options:
            auto_reload: %debug%
            cache: "%path.cache%/views"
            debug: %debug%
